### ISSUE TITLE
Component SEO was not imported, exported, or provided by MDXProvider as global scope

### ISSUE THREAD

**Issue by ahdinosaur** [ehowey/gatsby-theme-catalyst#595]
hi @ehowey, thanks for `gatsby-theme-catalyst`, i really appreciate the work you've done.

**Describe the bug**

when using a site built from the starter and updated to the last modules, in the console, i see:

```
Component SEO was not imported, exported, or provided by MDXProvider as global scope
```

and the page title isn't updated (which indicates the component isn't rendering).

so far i tracked this down to `gatsby-mdx-embed`, where the components from that module are in the context but not the `SEO` component given by `gatsby-theme-catalyst-core`. probably related to https://github.com/PaulieScanlon/gatsby-mdx-embed#setup, but i haven't tried to fix this yet.

**Comment by ehowey** [comment]
Hi @ahdinosaur thanks for the issue! Sorry this happened for you!

Unfortunately I can't replicate this on my end with the few quick tests I tried. Can you provide some more detail or a link to the repo? What do your starters with `gatsby-config.js` look like? What themes are you using?  

Another idea - and I assume you have tried this - is to delete your node_modules folder and yarn.lock and do a fresh package install.  Every once in a while I have run into weird errors due to conflicts in the node_modules folder that are resolved with this method.

**Comment by ehowey** [comment]
@ahdinosaur Just checking in - did either of those things fix it for you? Or still an issue?  I tried a few other things trying to reproduce this and haven't been able to.

**Comment by ahdinosaur** [comment]
hi @ehowey, yes doing a fresh yarn install resolved the issue. :sweat_smile: 

thanks for the help, i'm sorry for using your time on a non-issue. :heart: 

by the way, in case you're interested the `gatsby-theme-catalyst` site i'm working on is: https://github.com/villagekit/villagekit.com (live at [villagekit.com](https://villagekit.com)). :seedling:

**Comment by ehowey** [comment]
Awesome! Stoked to see that and cool to see what others are building. 

Also that just looks like a really cool project! I miss NZ. Travelled there for 3 months in my early 20s. It was a great time!

Take a look at ‘catalyst-blog’ v2.0 and there were quite a few improvements in there. But I also tried to remove some opinions and simplify. So when you update you will have to some shadowing to get back your blog layout. If you get stuck let me know and I can help.
